spring:
    application:
        name: exSawon


    datasource:
        driver-class-name: oracle.jdbc.OracleDriver
        url: jdbc:oracle:thin:@localhost:1521/xe
        username: C##TEST
        password: 1234		
# mapper.xml 위치 resources폴더 안에 mappers 폴더 생성
mybatis:
    mapper-locations: classpath:mappers.a/**/*.xml

